### ISSUE TITLE
     throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by tomoat** [garystafford/generator-node-restify-mongodb#4]
`events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/generator-node-restify-mongodb/generators/app/templates/.gitignore'
    at Object.fs.openSync (fs.js:557:18)
    at Function.module.exports.sync (/usr/local/lib/node_modules/generator-node-restify-mongodb/node_modules/read-chunk/index.js:34:14)
    at child.copy (/usr/local/lib/node_modules/generator-node-restify-mongodb/node_modules/yeoman-generator/lib/actions/actions.js:28:27)
    at child.projectfiles (/usr/local/lib/node_modules/generator-node-restify-mongodb/generators/app/index.js:61:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-node-restify-mongodb/node_modules/yeoman-generator/lib/base.js:439:23)
    at /usr/local/lib/node_modules/generator-node-restify-mongodb/node_modules/run-async/index.js:26:25
    at /usr/local/lib/node_modules/generator-node-restify-mongodb/node_modules/run-async/index.js:25:19
    at /usr/local/lib/node_modules/generator-node-restify-mongodb/node_modules/yeoman-generator/lib/base.js:440:9
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)`

**Comment by garystafford** [comment]
Did you try the latest version of the generator? This is a known issue with generators, which I thought I resolved in the latest version.

**Comment by lorismaz** [comment]
Got the same error with the last version from npm.

**Comment by jorgeas80** [comment]
Same problem here. Ubuntu 16.04 with those node and npm versions

v6.9.2
3.10.9

**Comment by jorgeas80** [comment]
Solved following the instructions here: https://github.com/garystafford/generator-node-restify-mongodb/issues/1

Basically, creating the missing .gitignore file
