### ISSUE TITLE
 Trying to copy from a source that does not exist: ....\generator-node-restify-mongodb\generators\app\templates\.gitignore

### ISSUE THREAD

**Issue by michaeldunnOMM** [garystafford/generator-node-restify-mongodb#6]
After installing 

npm install -g generator-node-restify-mongodb

I try

yo node-restify-mongodb

And I get the following error

AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: C:\Users\michael.dunn\AppData\Roaming\npm\node_modules\generator-node-restify-mongodb\generators\app\templates\.gitignore
    at EditionInterface.exports.copy (C:\Users\michael.dunn\AppData\Roaming\npm\node_modules\generator-node-restify-mongodb\node_modules\mem-fs-editor\lib\actions\copy.js:47:3)
    at module.exports.projectfiles (C:\Users\michael.dunn\AppData\Roaming\npm\node_modules\generator-node-restify-mongodb\generators\app\index.js:66:13)
    at Object.<anonymous> (C:\Users\michael.dunn\AppData\Roaming\npm\node_modules\generator-node-restify-mongodb\node_modules\yeoman-generator\lib\index.js:399:25)
    at C:\Users\michael.dunn\AppData\Roaming\npm\node_modules\generator-node-restify-mongodb\node_modules\run-async\index.js:25:25
    at new Promise (<anonymous>)
    at C:\Users\michael.dunn\AppData\Roaming\npm\node_modules\generator-node-restify-mongodb\node_modules\run-async\index.js:24:19
    at self.env.runLoop.add.completed (C:\Users\michael.dunn\AppData\Roaming\npm\node_modules\generator-node-restify-mongodb\node_modules\yeoman-generator\lib\index.js:400:11)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)

**Comment by mgcox2** [comment]
@michaeldunnOMM -> For some reason the .gitignore file is missing. You can simply create the file in the intended destination with the content from the corresponding .gitignore file in this repo. That should work fine. Hope this helps.
